# Generated by Django 4.2.4 on 2023-08-10 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role_position', models.CharField(max_length=255)),
                ('initial_application_submission_date', models.DateField()),
                ('application_type', models.CharField(choices=[('A', 'Type A Process'), ('B', 'Type B Process')], max_length=1)),
                ('result', models.CharField(blank=True, choices=[('O', 'Offer'), ('R', 'Rejected')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_interview_date', models.DateField(blank=True, null=True)),
                ('recruiter_interview_completed', models.BooleanField(default=False)),
                ('technical_interview_date', models.DateField(blank=True, null=True)),
                ('technical_interview_completed', models.BooleanField(default=False)),
                ('behavioural_interview_date', models.DateField(blank=True, null=True)),
                ('behavioural_interview_completed', models.BooleanField(default=False)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TypeA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_assessment_date', models.DateField(blank=True, null=True)),
                ('online_assessment_completed', models.BooleanField(default=False)),
                ('digital_interview_date', models.DateField(blank=True, null=True)),
                ('digital_interview_completed', models.BooleanField(default=False)),
                ('assessment_centre_date', models.DateField(blank=True, null=True)),
                ('assessment_centre_completed', models.BooleanField(default=False)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
    ]
