# Generated by Django 4.2.4 on 2023-08-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typea',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
    ]
